apiVersion: v1 #escrever pod o vs já dá o autocomplete
kind: Pod #tipo é um pod
metadata:
  name: nginx
  labels:
    name: nginx
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
      - containerPort: 80
    # resources:
    #   limits:
    #     memory: "128Mi"
    #     cpu: "500m"